# Generated by Django 2.2.6 on 2019-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191106_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
