# Generated by Django 2.2.6 on 2020-01-05 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_profile',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='billing_profile',
            name='stripe_id',
        ),
        migrations.AlterField(
            model_name='card',
            name='Billing_Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
