# Generated by Django 2.2.6 on 2019-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profile', '0002_auto_20191113_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_profile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
