# Generated by Django 2.2.6 on 2020-01-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profile', '0004_auto_20200105_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_profile',
            name='Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address'),
        ),
    ]
