# Generated by Django 2.2.6 on 2020-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200105_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sex',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100, null=True),
        ),
    ]
