# Generated by Django 2.2.6 on 2020-01-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200116_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='key_exp',
            field=models.IntegerField(default=1),
        ),
    ]
