# Generated by Django 2.2.6 on 2019-11-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-created'], 'verbose_name': 'Object Viewed', 'verbose_name_plural': 'Objects Viewed'},
        ),
    ]
