# Generated by Django 2.2.6 on 2019-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_profile',
            name='Card',
            field=models.ManyToManyField(blank=True, null=True, to='billing_profile.Card'),
        ),
    ]
