# Generated by Django 2.2.6 on 2019-11-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profile', '0003_billing_profile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_profile',
            name='Card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
