# Generated by Django 2.2.6 on 2019-11-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
