# Generated by Django 2.2.6 on 2019-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191104_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
