# Generated by Django 2.2.6 on 2019-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191105_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
