# Generated by Django 2.2.6 on 2020-01-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_profile',
            name='Email',
        ),
    ]
