# Generated by Django 2.2.6 on 2020-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='billing_profile',
            field=models.IntegerField(null=True),
        ),
    ]
