# Generated by Django 2.2.6 on 2019-11-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
    ]
