# Generated by Django 2.2.6 on 2020-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EMPLOYEE', 'EMPLOYEE'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=100),
        ),
    ]
