# Generated by Django 2.2.6 on 2020-01-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200104_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
